/**
 * Company group to SMARTwinFA licence number.
 *
 * menumaster decides which menus a company sees by licence number, and the
 * desktop derives that number from the company's CO_GROUP through a switch in
 * Setup_CompanySelect.cs. There is no table for it, so the mapping is ported
 * here verbatim; it belongs in the database and should move there once a
 * column exists for it. An unknown group gets 0, the desktop's default.
 */
const COMPANY_LICENCE: Readonly<Record<string, number>> = {
  "TRIMURTI": 1,
  "VINAYAK": 2,
  "DPG": 3,
  "DPA": 4,
  "SURFACE": 5,
  "COMET": 6,
  "SURF": 7,
  "SURFDECO": 8,
  "JITUBHAI": 9,
  "SJE": 10,
  "SJENT": 11,
  "ARIHANT": 12,
  "SURFOS": 13,
  "TJ": 14,
  "USA": 15,
  "SURF3": 16,
  "CHHAYA": 17,
  "SURFM3": 18,
  "AKSHAT": 19,
  "YOGI": 20,
  "RPI": 21,
  "MOONLAM": 22,
  "MSUR": 23,
  "SPAIN": 24,
  "RJENT": 25,
  "SRL": 26,
  "SIDDHI": 27,
  "PRITHVI": 28,
  "MULT": 29,
  "AIMLAM": 30,
  "AMBAIND": 31,
  "AMBA": 32,
  "OSWAL": 33,
  "MUDRA": 34,
  "RPIRND": 35,
  "RAINCOAT": 36,
  "SVC": 37,
  "AMBAFACT": 38,
  "ARHAMELE": 39,
  "AJMER": 40,
  "RAJGIRI": 41,
  "MAHAGURU": 42,
  "SKTIM": 43,
  "PRIHARI": 44,
  "ARITRADE": 45,
  "RPISALES": 46,
  "MANEK": 47,
  "VEERAS": 48,
  "VEER": 49,
  "SANVI": 50,
  "HITANSHI": 51,
  "MAYUR": 52,
  "MAYUDEMO": 53,
  "RATNASH": 54,
  "JITU": 55,
  "BHAKTILAM": 56,
  "BHAKTI": 57,
  "SAIPLY": 58,
  "RPIINV": 59,
  "DREAM": 60,
  "DREAMPLY": 61,
  "METADECOR": 62,
  "ANGEL": 63,
  "ANGAL": 64,
  "PDDEMO": 65,
  "SPDEMO": 66,
  "METROLAM": 67,
  "AIRA": 68,
  "GOLDEN": 69,
  "GOLDPLY": 70,
  "SJEFACT": 71,
  "METABACK": 72,
  "HEET": 73,
  "EVADECOR": 74,
  "SURINFRA": 75,
  "PRIBACK": 76,
  "EVABACK": 77,
  "AARTIENT": 78,
  "AARTIBACK": 79,
  "SJEFACTAC": 80,
  "BEARING": 81,
  "BHANDARI": 82,
  "WELCOME": 83,
  "WELCOM": 84,
  "SWASTIKIMP": 85,
  "SWASTIKWOD": 86,
  "NAINESH": 87,
  "SIGNATURE": 88,
  "SIGNAT": 89,
  "JAYESH": 90,
  "RATDEMO": 91,
  "KITOX": 92,
  "RAJDECOR": 93,
  "RAJDECB": 94,
  "PLYPALACE": 95,
  "KITOXB": 96,
  "DEVANSH": 97,
};

export function companyLicence(companyGroup: string | null | undefined) {
  return COMPANY_LICENCE[(companyGroup ?? "").trim().toUpperCase()] ?? 0;
}
